pages:
  - name: ホーム - 未来
    path: /2022-12-29
  - name: ホーム - 現在
    path: /
  - name: ホーム - 過去
    path: /2022-10-26
  - name: 出走表
    path: /races/99f2bca1-e909-4b1b-8f86-1b842b823b1c/race-card
  - name: オッズ - 締め切り前
    path: /races/99f2bca1-e909-4b1b-8f86-1b842b823b1c/odds
  - name: オッズ - 締め切り後
    path: /races/5cbce9e9-ccf0-4272-a831-8a17ad96fe47/odds
  - name: 結果
    path: /races/99f2bca1-e909-4b1b-8f86-1b842b823b1c/result
viewports:
  - name: Pixel 5
    width: 393
    height: 851
  - name: Kindle Fire HDX
    width: 800
    height: 1280
  - name: Desktop
    width: 1280
    height: 720
